### ISSUE TITLE
Add sample usage to README

### ISSUE THREAD

**Issue by jonwbstr** [corydwood/MicrosoftPartnerCenterAPI#1]
Install-Module MicrosoftPartnerCenterAPI
Import-Module MicrosoftPartnerCenterAPI

Follow the example below to get and then update a partner subscription quantity:

```
# Create token using application created in prereq's
$mpcToken = Get-MPCToken -ApplicationID f5e4f291-6e60-48c0-bc2e-e72e9a3a0464 -Credential (Get-Credential)

# Retrieve a Subscription
$mpcSubscription = (Get-MPCSubscriptions -MPCToken $mpcToken.access_token -CustomerID e2dcbfa5-cc31-4062-a76f-34b4c2e92a72).items | select -First 1

# Update quantity of subscription
Update-MPCSubscription -MPCToken $mpcToken -CustomerID e2dcbfa5-cc31-4062-a76f-34b4c2e92a72 -Subscription $mpcSubscription -Quantity 5
```

**Comment by corydwood** [comment]
Hi @jonwbstr,

Those examples are saved within the PSM1 file itself in the comment-based help. I didn't put them in the README because I didn't want duplicate information.

Also, I haven't put much more work into this module because shortly after I published it, Microsoft created their own: https://github.com/Microsoft/PartnerCenterPowerShellModule. Theirs is more complete.

**Comment by jonwbstr** [comment]
Understandable, thanks for the reply!

For future reference the readme goes into howto install the module but not
how to use it to do anything, the section that says what to do next is what
I was looking for. The only option left was to look at the commands with
interesting names and *HOPE* there was more detail. I say hope because the
readme doesn't indicate examples would be in those files or anything.
Figured it out by guessing the right command and guessing the examples
would be useful. This level of documentation is fine for people that know
how to write modules, less so for people that have very little experience
with powershell.

We didn't need the other functionality for the current project, and found
your solution a bit easier to use. Thanks for leaving it up!

You may want to direct people to the alternative module if you prefer to
let this die out.

Regards,
-jon
